#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]]	
		then
			if [[ $cur == "I watched Avengers: Endgame. Thanos d**s..." ]]
			then
				echo "Spoiler Alert!"
				prev=$cur
				continue
			fi
			echo $cur
			prev=$cur
		fi
	fi
done
